# Generated by Django 4.0.1 on 2022-01-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelemetricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_temperature', models.CharField(max_length=225, verbose_name='Engine Temperature')),
                ('car_speed', models.CharField(max_length=225, verbose_name='Car Spedd')),
                ('car_gps_lat', models.CharField(max_length=225, verbose_name='Car GPS Latitide')),
                ('car_gps_lon', models.CharField(max_length=225, verbose_name='Car GPS Longitude')),
                ('fuel_consumption_rate', models.CharField(max_length=225, verbose_name='Fuel Consumption Rate')),
                ('accelerometer', models.CharField(max_length=225, verbose_name='Car Accelerometer')),
                ('steering_angle', models.CharField(max_length=225, verbose_name='Car Steering Angle')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
